robinrodricks/FluentFTP.GnuTLS

FluentFTP.GnuTLS/Core/GnuTls.cs
FluentFTP.GnuTLS/Core/GnuUtils.cs
FluentFTP.GnuTLS/Core/Logging.cs
FluentFTP.GnuTLS/GnuTlsStream/GnuTlsInternalStream.cs
FluentFTP.GnuTLS/GnuTlsStream/Helpers/HandshakeHook.cs
FluentFTP.GnuTLS/GnuTlsStream/Helpers/PopulateHandshakeInfo.cs
FluentFTP.GnuTLS/GnuTlsStream/Helpers/ReportClientCertificateUsed.cs
FluentFTP.GnuTLS/GnuTlsStream/Helpers/SetupHandshake.cs
FluentFTP.GnuTLS/GnuTlsStream/Helpers/ValidateServerCertificates.cs

Some renames/refactors
Add transport_set_int2 as alternative
**Transport set functions are return type void**

Try to fix #1218

---

FluentFTP.GnuTLS/FluentFTP.GnuTLS.csproj

This was turned on for debugging. No longer necessary...

Only generate package on Release build

---

FluentFTP.GnuTLS/Core/GnuTls.cs
FluentFTP.GnuTLS/GnuTlsStream/GnuTlsInternalStream.cs
FluentFTP.GnuTLS/GnuTlsStream/Helpers/ValidateServerCertificates.cs

To solve some problems with FluentFTP client **reuse** szenarios

Rearrange ctor/dtor logic and gnutls_free

---

FluentFTP.GnuTLS/Core/GnuTls.cs

Effectively: Remove the return statement, reactivate the code.

Reactivate fixed & tested gnutls_free logic

---

FluentFTP.GnuTLS/Core/GnuTls.cs

Reverts robinrodricks/FluentFTP.GnuTLS#49

Revert "Cleanup access modifiers"

---

FluentFTP.GnuTLS/Core/GnuTls.cs
FluentFTP.GnuTLS/Core/GnuTlsLin.cs
FluentFTP.GnuTLS/Core/GnuTlsWin.cs
FluentFTP.GnuTLS/GnuTlsStream/GnuTlsInternalStream.cs

Reverts robinrodricks/FluentFTP.GnuTLS#48
Linux calls are still unstable. I will debug using the previous context.

Revert "Refactor / Redesign native library calls to avoid duplication"

---

FluentFTP.GnuTLS/Core/GnuTls.cs

All preparations for the big change from if-then-else DllImport switching to using pre-loaded delegates into the library are complete.

Marker commit: Linux support pre FunctionLoader technology

---

FluentFTP.GnuTLS/FluentFTP.GnuTLS.csproj
RELEASES.md

Release the big switch to using delegates

release 1.0.10

---

FluentFTP.GnuTLS/Core/GnuTls.cs
FluentFTP.GnuTLS/GnuTlsStream/GnuTlsInternalStream.cs

Solve the problem of "SIGNER NOT FOUND" on certificate validation

Add setting up System Trust List

---

FluentFTP.GnuTLS/Core/GnuTls.cs
FluentFTP.GnuTLS/GnuTlsStream/GnuTlsInternalStream.cs

For repeated client create - dispose sequences

Re-Load all static function pointers before validation

---

FluentFTP.GnuTLS/FluentFTP.GnuTLS.csproj
RELEASES.md

Re-release of 1.0.15, no changes

release 1.0.16

---

FluentFTP.GnuTLS/Core/GnuTls.cs

Improve FunctionLoad for Azure

---

FluentFTP.GnuTLS/Core/GnuTls.cs

Allow E_FILE_ERROR on set_x509_system_trust

---

FluentFTP.GnuTLS/Libs/Helpers/FluentFTP.GnuTLS.targets

Copy for lib dlls to publish dir to support dotnet publish command

---

FluentFTP.GnuTLS/FluentFTP.GnuTLS.csproj
RELEASES.md

- Add copy for non-managed dlls to publish dir to support dotnet publish command

release 1.0.20

---

FluentFTP.GnuTLS/Core/GnuTls.cs
FluentFTP.GnuTLS/Core/Logging.cs
FluentFTP.GnuTLS/GnuConfig.cs
FluentFTP.GnuTLS/GnuTlsStream.cs
FluentFTP.GnuTLS/GnuTlsStream/GnuTlsInternalStream.cs

Clean up Use-Count logic, move up one tier
Config variable, which has gone through some changes, now obsolete
Currently disable library free because of bug described in #100

Clean up usecount logic

---

RELEASES.md

- Some more logging tweaks and small code cleanup changes.

release 1.0.23

---

FluentFTP.GnuTLS/FluentFTP.GnuTLS.csproj
RELEASES.md

- Updates to TFMs, NuGet packages and build/packaging process.

release 1.0.25

---

FluentFTP.GnuTLS/FluentFTP.GnuTLS.csproj
FluentFTP.GnuTLS/Libs/Helpers/FluentFTP.GnuTLS.targets

Fixup and revise .csproj NuGet related settings

release 1.0.26

---

FluentFTP.GnuTLS/Core/GnuTls.cs
FluentFTP.GnuTLS/GnuTlsStream/GnuTlsInternalStream.cs

If you set 
```cs
LoadLibraryDllNamePrefix = "ClickOnceSingleFile"
```
in the config, this will become active.

Added logic for ClickOnceSingleFile

---

FluentFTP.GnuTLS/Core/GnuTls.cs

Ignore BYE error INVALID SESSION
